# Generated by Django 3.1.3 on 2020-11-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_opengraph_image_generator', '0003_auto_20200421_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opengraphimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.alttextimage'),
        ),
        migrations.AlterField(
            model_name='opengraphimagegeneratorsettings',
            name='company_logo',
            field=models.ForeignKey(blank=True, help_text='Will be added to the top left of every OpenGraph image.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.alttextimage'),
        ),
        migrations.AlterField(
            model_name='opengraphimagegeneratorsettings',
            name='company_logo_alternative',
            field=models.ForeignKey(blank=True, help_text='Alternative version of your logo for the dark OpenGraph image variant. You may want to supply a differently colored logo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.alttextimage'),
        ),
        migrations.AlterField(
            model_name='opengraphimagegeneratorsettings',
            name='default_background_image',
            field=models.ForeignKey(blank=True, help_text='Will be used as a fallback background image for your OpenGraph images if no model specific image field has been defined.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.alttextimage'),
        ),
    ]
